#!/usr/bin/env python3
"""mimosa_size counterpart of generate_latex_tables.py.

Reads the same `reproduction-comparison.xlsx` workbook, but instead of the
paper's model roster (which excludes the mimosa_size family entirely --
see EXCLUDED_MODELS in generate_latex_tables.py) this script includes
*only* the mimosa_size compute-scaling sweep: mimosa_micro, mimosa_tiny,
mimosa_small, mimosa_medium, mimosa_base, mimosa_large, mimosa_huge,
mimosa_gargantuan. There's no legacy reference for these (they're baselines
generated by this pipeline, not literature numbers), so every table only
ever shows the reproduced mean +/- std -- structurally the same situation
as generate_latex_tables.py's MB-96 section, so this reuses its fused
(WT/TC/ET stacked with a rotated region label) table layout via
build_mb96_table, just pointed at BRATS2018/BRATS2023 instead of the
internal MB-96 dataset. It also emits its own MB-96 section (checkpoints
trained on BRATS2018/BRATS2023, evaluated against the internal dataset),
same as generate_latex_tables.py's, but restricted to the mimosa_size
family and ordered along its capacity ladder.

Writes tables.tex + main.tex into OUTPUT_DIR and compiles to PDF with
tectonic, same as generate_latex_tables.py.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generate_latex_tables as glt  # noqa: E402

OUTPUT_DIR = os.path.join(glt.RESULTS_DIR, "latex_tables_mimosa_size")

# True capacity ladder (by params/FLOPs, see mimosa_*_23.yaml
# features_per_stage), not alphabetical -- this is the order the family is
# discussed in the paper text, so tables should match.
MIMOSA_SIZES = ("micro", "tiny", "small", "medium", "base", "large", "huge", "gargantuan")
SIZE_DISPLAY = {size: f"mimosa\\_{size}" for size in MIMOSA_SIZES}
SIZE_ORDER = {size: i for i, size in enumerate(MIMOSA_SIZES)}


def load_mimosa_size(path):
    """Like glt.load_all, but keeps only the mimosa_size sheets (bypassing
    EXCLUDED_MODELS, which excludes this family from the main tables)."""
    import openpyxl

    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    wanted = {f"mimosa{size}": size for size in MIMOSA_SIZES}
    models = {}
    for name in wb.sheetnames:
        norm = glt.normalize_name(name)
        if norm in wanted:
            models[SIZE_DISPLAY[wanted[norm]]] = glt.parse_sheet(wb[name])
    return models


def sort_by_size(model_names):
    def key(name):
        size = name.split("\\_", 1)[1]
        return SIZE_ORDER.get(size, len(SIZE_ORDER))

    return sorted(model_names, key=key)


def _build_family_body(models, dataset, metric, use_internal):
    """Shared fused-region (WT/TC/ET) row-building for both the BRATS and
    MB-96 mimosa_size tables: same G column type / rank-wrapping / rotated
    region label via \\multirow, rows sorted along the capacity ladder
    rather than alphabetically. Returns (body_lines, header_mkeys,
    header_mods) or None if the dataset has no data at all."""
    lower_better = metric == "HD95"

    region_blocks = []
    for region in glt.REGIONS:
        mkeys, row_records = glt.collect_row_records(
            models, dataset, region, metric, source="repro", use_internal=use_internal
        )
        if mkeys is None:
            return None
        by_name = {r[0]: r[1:] for r in row_records}
        ordered_names = sort_by_size(by_name.keys())
        row_records = [(name, *by_name[name]) for name in ordered_names]
        region_blocks.append((mkeys, row_records))

    header_mkeys = region_blocks[0][0]
    header_mods = " & ".join(glt.modality_label(k) for k in header_mkeys)

    body = []
    for region, (mkeys, row_records) in zip(glt.REGIONS, region_blocks):
        n_cols = len(mkeys)
        col_best_second = [
            glt.ranked_indices([r[1][c][1] for r in row_records], lower_better=lower_better)
            for c in range(n_cols)
        ]
        avg_best, avg_second = glt.ranked_indices(
            [r[2][1] for r in row_records], lower_better=lower_better
        )

        n_rows = len(row_records)
        for i, (name, cells, avg_cell, _diff_text) in enumerate(row_records):
            cell_texts = [
                glt.rank_wrap(text, i, *col_best_second[c]) for c, (text, _) in enumerate(cells)
            ]
            avg_text = glt.rank_wrap(avg_cell[0], i, avg_best, avg_second)
            region_col = (
                f"\\multirow{{-{n_rows}}}{{*}}{{\\rotatebox{{90}}{{\\textbf{{{glt.REGION_DISPLAY[region]}}}}}}}"
                if i == n_rows - 1
                else ""
            )
            row_cells = [region_col, name] + cell_texts + [avg_text]
            body.append(" & ".join(row_cells) + r" \\")
        if region != glt.REGIONS[-1]:
            body.append(r"\midrule")

    return body, header_mkeys, header_mods


def _wrap_family_table(body, header_mkeys, caption, combined_label, region_labels):
    colspec = "cl" + "*{" + str(len(header_mkeys)) + "}{G}" + "!{\\vrule width 0.6pt}c"

    lines = [
        r"\begin{table*}[!ht]",
        r"\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{combined_label}}}",
        *region_labels,
        r"\resizebox{\textwidth}{!}{%",
        r"\begingroup",
        r"\renewcommand{\arraystretch}{1.3}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\rowcolors{2}{white}{gray!6}",
        f"\\begin{{tabular}}{{{colspec}}}",
        r"\toprule",
        r"\MissingModalityHeaderWithRegion",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\endgroup",
        r"}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(lines)


def build_family_table(models, dataset, metric):
    """Fused WT/TC/ET table for one (dataset, metric), rows sorted along
    the mimosa_size capacity ladder rather than alphabetically. Structurally
    identical to glt.build_mb96_table (same fused-region layout, same G
    column type / \\MissingModalityHeaderWithRegion macro), but reads
    dataset directly (BRATS2018/BRATS2023) instead of the internal MB-96
    columns, and has no legacy reference to compare against."""
    result = _build_family_body(models, dataset, metric, use_internal=False)
    if result is None:
        return ""
    body, header_mkeys, header_mods = result

    unit = "\\%" if metric == "Dice" else " (mm)"
    caption = (
        f"{metric}{unit} for WT, TC, and ET on the {dataset} dataset for the "
        "mimosa\\_size compute-scaling family (mean $\\pm$ std over the "
        "reproduced folds; no legacy reference -- these are baselines "
        "generated by this pipeline, not literature numbers)."
    )
    combined_label = f"tab:mimosa_size_{dataset.lower()}_{metric.lower()}_all_regions"
    region_labels = [
        f"\\label{{tab:mimosa_size_{dataset.lower()}_{region.lower()}_{metric.lower()}}}"
        for region in glt.REGIONS
    ]

    table = _wrap_family_table(body, header_mkeys, caption, combined_label, region_labels)
    return table, header_mods


def build_family_mb96_table(models, dataset, metric):
    """MB-96 counterpart of build_family_table: fused WT/TC/ET table
    evaluating checkpoints trained on `dataset` (BRATS2018/BRATS2023)
    against the internal MB-96 dataset, rows sorted along the mimosa_size
    capacity ladder. Mirrors glt.build_mb96_table but keeps only the
    mimosa_size family and its capacity-ladder row order."""
    result = _build_family_body(models, dataset, metric, use_internal=True)
    if result is None:
        return ""
    body, header_mkeys, header_mods = result

    dataset_short = glt.DATASET_SHORT[dataset]
    unit = "\\%" if metric == "Dice" else " (mm)"
    caption = (
        f"{metric}{unit} for WT, TC, and ET on the MB-96 dataset using "
        f"checkpoints trained on {dataset_short}, for the mimosa\\_size "
        "compute-scaling family (mean $\\pm$ std across the split-specific "
        "checkpoints; no legacy reference -- these are baselines generated "
        "by this pipeline, not literature numbers)."
    )
    combined_label = f"tab:mimosa_size_mb96_{dataset_short}_{metric.lower()}_all_regions"
    region_labels = [
        f"\\label{{tab:mimosa_size_mb96_{dataset_short}_{region.lower()}_{metric.lower()}}}"
        for region in glt.REGIONS
    ]

    table = _wrap_family_table(body, header_mkeys, caption, combined_label, region_labels)
    return table, header_mods


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    models = load_mimosa_size(glt.WORKBOOK)
    if not models:
        print("No mimosa_size sheets found in the workbook", file=sys.stderr)
        return

    sections = [r"\section*{mimosa\_size}"]
    header_macro = None
    for dataset in glt.DATASETS:
        for metric in glt.METRICS:
            result = build_family_table(models, dataset, metric)
            if not result:
                continue
            table, header_mods = result
            if header_macro is None:
                header_macro = (
                    r"\newcommand{\MissingModalityHeaderWithRegion}{"
                    f" & \\textbf{{Model}} & {header_mods} & \\textbf{{Avg.}} \\\\"
                    "}"
                )
            sections.append(table)
            sections.append(r"\clearpage")

    sections.append(r"\section*{MB-96}")
    for dataset in glt.DATASETS:
        for metric in glt.METRICS:
            result = build_family_mb96_table(models, dataset, metric)
            if not result:
                continue
            table, header_mods = result
            if header_macro is None:
                header_macro = (
                    r"\newcommand{\MissingModalityHeaderWithRegion}{"
                    f" & \\textbf{{Model}} & {header_mods} & \\textbf{{Avg.}} \\\\"
                    "}"
                )
            sections.append(table)
            sections.append(r"\clearpage")

    tables_path = os.path.join(OUTPUT_DIR, "tables.tex")
    with open(tables_path, "w") as f:
        if header_macro:
            f.write(header_macro + "\n\n")
        f.write("\n".join(sections))

    main_tex = r"""\documentclass[10pt]{article}
\usepackage[margin=1.2cm]{geometry}
\usepackage{array}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{makecell}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage[table]{xcolor}
\usepackage{tikz}
\usepackage{lmodern}
\newcolumntype{G}{!{\color{gray!35}\vrule width 0.4pt}c}
\pagestyle{plain}
\begin{document}
\input{tables.tex}
\end{document}
"""
    main_path = os.path.join(OUTPUT_DIR, "main.tex")
    with open(main_path, "w") as f:
        f.write(main_tex)

    print(f"Wrote {tables_path}")
    print(f"Wrote {main_path}")

    glt.compile_pdf(main_path)


if __name__ == "__main__":
    main()
